pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'
  imageName: 'eltonpontes-devops:latest'

steps:
- script: dotnet restore
  displayName: 'Packages'

- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'Building'

- task: DotNetCoreCLI@2
  displayName: 'Testing'
  inputs:
    command: test
    projects: '**/*Tests/*.csproj'
    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

- script: docker build --no-cache -f Dockerfile -t $(dockerId)/$(imageName) .
  displayName: 'Building Docker'

- script: |
    docker login -u $(dockerId) -p $(dockerPassword)
    docker push $(dockerId)/$(imageName)
  displayName: 'Sending to Docker Hub'